# Generated by Django 6.0.1 on 2026-02-03 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('count_type', models.CharField(choices=[('area_perimeter', 'Area & Perimeter'), ('linear_feet', 'Linear Feet'), ('each', 'Each')], max_length=32)),
                ('color', models.CharField(default='#00ff00', max_length=32)),
                ('shape', models.CharField(blank=True, max_length=16)),
                ('trade', models.CharField(choices=[('acoustic', 'Acoustic'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('mechanical', 'Mechanical'), ('other', 'Other')], default='other', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='plans/pages/')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='PlanSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='plans/pdfs/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.CharField(choices=[('acoustic', 'Acoustic'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('mechanical', 'Mechanical'), ('other', 'Other')], max_length=32)),
                ('geometry', models.JSONField()),
                ('score', models.FloatField(default=0.0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('count_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.countdefinition')),
                ('plan_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.planpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.CharField(choices=[('acoustic', 'Acoustic'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('mechanical', 'Mechanical'), ('other', 'Other')], max_length=32)),
                ('image', models.ImageField(upload_to='datasets/examples/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('count_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.countdefinition')),
                ('plan_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_examples', to='core.planpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometry_type', models.CharField(max_length=32)),
                ('geometry', models.JSONField()),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('perimeter_ft', models.FloatField(blank=True, null=True)),
                ('length_ft', models.FloatField(blank=True, null=True)),
                ('count_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.countdefinition')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_items', to='core.planpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planpage',
            name='plan_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.planset'),
        ),
        migrations.AddField(
            model_name='countdefinition',
            name='plan_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_definitions', to='core.planset'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sets', to='core.project'),
        ),
        migrations.CreateModel(
            name='ScaleCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('real_world_feet', models.FloatField()),
                ('pixel_distance', models.FloatField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scale', to='core.planpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='planpage',
            unique_together={('plan_set', 'page_number')},
        ),
    ]
