# Generated by Django 5.2.6 on 2026-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_countitem_rotation_deg_alter_contactmessage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpage',
            name='dpi_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planpage',
            name='dpi_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
