# Generated by Django 5.2.6 on 2026-02-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_privacyagreement_subscription_tradedataset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countitem',
            name='is_auto_detected',
            field=models.BooleanField(default=False),
        ),
    ]
