# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_countitem_is_auto_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='planset',
            name='processing_pages_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planset',
            name='processing_pages_done',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
