# Generated by Django 5.2.6

from django.db import migrations, models


def set_max_team_members_to_3(apps, schema_editor):
    Subscription = apps.get_model("core", "Subscription")
    Subscription.objects.update(max_team_members=3)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_planset_processing_pages'),
    ]

    operations = [
        migrations.RunPython(set_max_team_members_to_3, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='subscription',
            name='max_team_members',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
