# Generated by Django 5.2.6

from django.db import migrations


def update_team_members_by_plan(apps, schema_editor):
    Subscription = apps.get_model("core", "Subscription")
    # Update existing subscriptions based on their plan
    for sub in Subscription.objects.all():
        if sub.plan == 'business':
            sub.max_team_members = 50
        elif sub.plan == 'pro':
            sub.max_team_members = 3
        else:  # free
            sub.max_team_members = 3
        sub.save(update_fields=['max_team_members'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subscription_max_team_members_3'),
    ]

    operations = [
        migrations.RunPython(update_team_members_by_plan, migrations.RunPython.noop),
    ]
