# Generated by Django 5.2.11 on 2026-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_datasetexample_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetexample',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro ($49/mo)'), ('business', 'Business ($149/mo)')], default='free', max_length=32),
        ),
    ]
