# Generated by Django 5.2.6 on 2026-03-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contactmessage_id_alter_countdefinition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimating_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='ProjectEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('body_preview', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('invite', 'Bid Invitation'), ('change', 'Change / Addendum'), ('general', 'General')], default='general', max_length=16)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.project')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
