# Generated by Django 5.2.6 on 2026-03-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_estimating_email_and_project_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdefinition',
            name='shape_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
