# Generated by Django 5.2.6 on 2026-03-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_count_definition_shape_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpage',
            name='image_alt',
            field=models.ImageField(blank=True, null=True, upload_to='plans/pages_alt/'),
        ),
    ]
