# Generated by Django 5.2.6 on 2026-03-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_plan_page_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdefinition',
            name='shape_image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
