# Generated by Django 5.2.6 on 2026-03-09 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_count_definition_shape_image_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdefinition',
            name='shape_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='PlanPageOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='plans/pages_overlays/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='core.planpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
