# Generated by Django 5.2.6 on 2026-03-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_plan_page_overlays'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpage',
            name='image_alt_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='planpageoverlay',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
