# Generated by Django 5.2.6 on 2026-03-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_extra_image_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpage',
            name='image_alt_offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='planpage',
            name='image_alt_offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='planpage',
            name='image_alt_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='planpageoverlay',
            name='offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='planpageoverlay',
            name='offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='planpageoverlay',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
    ]
